mgr/urls.py
from django.conf.urls import patterns, include, url
from mgr import views

urlpatterns = patterns(
    '',
    url(r'^$', views.main_page, name='main_page'),
    url(r'^allquestions$', views.all_questions, name='all_questions'),
    url(r'^statistics', views.display_statistics, name='display_statistics'),
    url(r'^options', views.display_options, name='display_options'),
    url(r'^createtest', views.create_test, name='create_test'),
    url(r'^choosedepartment$', views.choose_department, name='choose_department'),
    url(r'^showfieldofquestion/(\d+)$', views.show_field_of_question, name='show_field_of_questions'),
    url(r'^workonquestion/?$', views.work_on_question, name='work_on_questions'),
    url(r'^savequestion/(?P<question_id>(\d+))/(?P<accept>(\w+))/?$', views.save_question, name='save_question'),
    url(r'^acceptquestion/?$', views.accept_question, name='accept_question'),
    url(r'^loadquestions/(?P<field_of_question_id>(\d+))/?$', views.load_questions_field_of_question, name='load_questions'),
    url(r'^starttest/(?P<field_of_question>(\w+))/?', views.start_test, name='start_test'),
    url(r'^checkanswers/?', views.check_answers, name='check_answers'),
    url(r'^display_results/(?P<answers>(\d+))/(?P<correct_answers>(\d+))/?', views.display_results, name='display_results'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
)

mgr/models.py
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models


class Department(models.Model):
    name = models.CharField(max_length=40, blank=False, null=False, default='Wydzial Fizyki i Informatyki Stosowanej')
    shortcut = models.CharField(max_length=10, blank=False, null=False, default='WFIIS')
    home_page = models.URLField(blank=False, null=False, default='http://www.ftj.agh.edu.pl/')

    def __unicode__(self):
        return self.name


class FieldOfStudy(models.Model):
    name = models.CharField(max_length=30, blank=False, null=False, default='Informatyka Stosowana')
    department = models.ForeignKey(Department, default=1)

    class Meta:
        verbose_name_plural = 'Field of studies'

    def __unicode__(self):
        return self.name


class FieldOfQuestion(models.Model):
    name = models.CharField(max_length=40, blank=False, null=False, default='Dziedzina pytania')
    field_of_study = models.ForeignKey(FieldOfStudy)
    number_of_questions = models.IntegerField(default=0, blank=False, null=True)
    shortcut = models.CharField(max_length=5, blank=False, null=False, default='')

    def __unicode__(self):
        return '%s - %s ' % (self.field_of_study.name, self.name)


class Answer(models.Model):
    value = models.CharField(max_length=200, blank=False, null=False, default='Put your answer here!')
    correct = models.BooleanField(default=False)

    def __unicode__(self):
        return '%s' % self.value


class Question(models.Model):
    question_number = models.IntegerField(default=0, blank=False, null=False)
    field_of_question = models.ForeignKey(FieldOfQuestion, related_name="fieldofquestion")
    value = models.CharField(max_length=255, unique=True, blank=False, null=False, default='Put you question here!')
    # image = models.ImageField(upload_to='attachments', blank=True, null=True)
    answer_1 = models.ForeignKey(Answer, related_name='A', blank=True, null=True)
    answer_2 = models.ForeignKey(Answer, related_name='B', blank=True, null=True)
    answer_3 = models.ForeignKey(Answer, related_name='C', blank=True, null=True)
    answer_4 = models.ForeignKey(Answer, related_name='D', blank=True, null=True)
    approved_by_admin = models.BooleanField(default=False, blank=True)
    is_prepared = models.BooleanField(default=False, blank=True)

    def __unicode__(self):
        return '%s - %s ' % (self.field_of_question, self.value)


class UserProfile(AbstractUser):
    question_prepared = models.ManyToManyField(Question, blank=True, related_name="prepared_by")


class CustomTest(models.Model):
    name = models.CharField(max_length=40, blank=False, null=False, unique=True, default='Przykladowy test')
    questions = models.ManyToManyField(Question, related_name="Pytania", verbose_name="questions")
    approved_by_admin = models.BooleanField(default=False, blank=True)


class Statistic(models.Model):
    correct_answers = models.IntegerField(default=0, blank=False, null=False)
    all_answers = models.IntegerField(default=0, blank=False, null=False)
    user = models.ForeignKey(UserProfile, related_name="user_stats")
    field_of_question = models.ForeignKey(FieldOfQuestion, blank=True, null=True, related_name="field_stats")
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __unicode__(self):
        return "%s - %s - %s" % (self.user, self.field_of_question, self.date)

mgr/forms.py
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.forms import ModelForm, HiddenInput
from mgr.models import Question, CustomTest


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
        widgets = {
            'question_number': HiddenInput(),
            'value': HiddenInput(),
            'is_prepared': HiddenInput(),
            'answer_1': HiddenInput(),
            'answer_2': HiddenInput(),
            'answer_3': HiddenInput(),
            'answer_4': HiddenInput(),
            'field_of_question': HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        # self.fields['image'].widget = HiddenInput()
        self.fields['approved_by_admin'].widget = HiddenInput()
        self.fields['question_number'].widget.attrs.update({'readonly': 'True'})
        self.fields['value'].widget.attrs.update({'readonly': 'True'})
        self.fields['field_of_question'].widget.attrs.update({'readonly': 'True'})
        self.fields['answer_1'].widget.attrs.update({'readonly': 'True'})
        self.is_prepared = True

        for key in self.fields:
            self.fields[key].widget.attrs.update({'class': 'form-control'})


class CustomTestForm(ModelForm):
    questions = forms.ModelMultipleChoiceField(Question.objects.all(),
                                               widget=FilteredSelectMultiple('Questions', False, attrs={'rows': 10}))

    class Meta:
        fields = '__all__'
        model = CustomTest

mgr/views.py
import codecs
import random
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
import time
from mgr.forms import QuestionForm
from mgr.models import Department, FieldOfStudy, FieldOfQuestion, Question, Answer, UserProfile, CustomTest, Statistic
from django.contrib import messages


@login_required
def main_page(request):
    """
    Function representing main page.
    :param request: Page request
    :return: Main page
    """
    return render_to_response('main_page.html', {}, RequestContext(request))


@login_required()
def all_questions(request):
    """
    Function representing all questions in the system.
    :param request: Page request
    :return: Return page with all questions in the application
    """
    return render_to_response('mgr/all_questions.html', {}, RequestContext(request))


@login_required()
def choose_department(request):
    """
    Function which handles choosing the right department
    :param request: Page request
    :return: Page on which you can choose department and also field of study
    """
    if request.POST:
        return redirect('mgr.views.show_field_of_question', request.POST.get('field_of_study'))

    departments = Department.objects.all()
    field_of_study = FieldOfStudy.objects.all()
    return render_to_response('mgr/choose_department.html', {
        'departments': departments,
        'field_of_study': field_of_study
    }, RequestContext(request))


@login_required()
def show_field_of_question(request, field_of_study_id):
    """
    Function which represents charts for the given field of study or field of question or custom test
    :param request: Page request
    :param field_of_study_id: Filed of study id
    :return: Page with charts representing all questions for given field of study and also tests for all fields of question
    """
    field_of_question = FieldOfQuestion.objects.filter(field_of_study__id=field_of_study_id)
    custom_test = CustomTest.objects.filter(approved_by_admin=True)
    questions_for_field = []
    color_list = ['#98df8a', '#d62728', '#ffbb78']  # opracowane, nieopracowane, przygotowane
    chart_type = "pieChart"
    extra_series = {"tooltip": {"y_start": "", "y_end": " pytan"}, 'color': '#FF8aF8'}

    for question_field in field_of_question:
        questions = Question.objects.filter(field_of_question=question_field)
        questions_approved = len(questions.filter(approved_by_admin=True))
        questions_prepared = len(questions.filter(is_prepared=True, approved_by_admin=False))
        questions_not_ready = len(questions.filter(is_prepared=False, approved_by_admin=False))
        dictionary = {
            'field_of_study': question_field.name,
            'questions_not_ready': questions_not_ready,
            'questions_approved': questions_approved,
            'questions_prepared': questions_prepared,
        }
        questions_for_field.append(dictionary)
    questions_approved = len(Question.objects.filter(field_of_question__in=field_of_question, approved_by_admin=True))
    questions_not_ready = len(Question.objects.filter(field_of_question__in=field_of_question, is_prepared=False, approved_by_admin=False))
    questions_prepared = len(Question.objects.filter(field_of_question__in=field_of_question, is_prepared=True, approved_by_admin=False))
    x_data = ['Opracowane', 'Nieopracowane', 'Przygotowane']
    y_data = [[questions_approved, questions_not_ready, questions_prepared]]
    for item in questions_for_field:
        y_data.append(item.values()[1:])
    chart_data = []
    for test in custom_test:
        chart_data.append({'x': x_data, 'y': [len(test.questions.all()), 0, 0], 'extra': extra_series})

    chart_data_0 = {'x': x_data, 'y': y_data[0], 'extra': extra_series}
    chart_data_1 = {'x': x_data, 'y': y_data[1], 'extra': extra_series}
    chart_data_2 = {'x': x_data, 'y': y_data[2], 'extra': extra_series}
    data = {
        'chart_type': chart_type,
        'chart_data': chart_data,
        'chart_data_0': chart_data_0,
        'chart_data_1': chart_data_1,
        'chart_data_2': chart_data_2,
        'extra': {
            'x_is_date': False,
            'x_axis_format': '',
            'tag_script_js': True,
            'jquery_on_ready': False,
            'chart_attr': {'color': color_list, 'labelType': '"percent"'},
            'donut': True,
        },
    }
    return render_to_response('mgr/field_of_question.html', data, RequestContext(request))


@login_required()
def work_on_question(request):
    """
    Function which handles updating questions with the wrong answers
    :param request: Page request
    :return: Page on which user can work on questions by providing wrong answers for random question
    """
    user = UserProfile.objects.get(id=request.user.id)
    questions_without_answer = Question.objects.filter(approved_by_admin=False, is_prepared=False)
    questions_to_do_id = [question_id.id for question_id in questions_without_answer]
    if questions_to_do_id:
        random_id = random.choice(questions_to_do_id)
        random_question = Question.objects.get(id=random_id)
        form = QuestionForm(instance=random_question)
    else:
        form = random_question = None
    questions_done = user.question_prepared.count()
    return render_to_response('mgr/work_on_questions.html', {
        'questions_without_answer': questions_without_answer,
        'count_questions': len(questions_to_do_id),
        'form': form,
        'question': random_question,
        'questions_done': questions_done,
    }, RequestContext(request))


@login_required()
def save_question(request, question_id, accept=False):
    """
    Function which handles saving questions or updating
    :param request: Page request
    :param question_id: Question ID
    :param accept: Boolean field representing if the questions was accepted by admin or not. This function is reused in few placed that's why here we have 3
                    arguments so it can be more generic.
    :return:
    """
    user = UserProfile.objects.get(id=request.user.id)
    question = Question.objects.get(id=question_id)
    if request.method == 'POST':
        form = QuestionForm(instance=question, data=request.POST)
        if form.is_valid():
            answer_2, created = Answer.objects.get_or_create(value=request.POST.get('answer_B'))
            answer_3, created = Answer.objects.get_or_create(value=request.POST.get('answer_C'))
            answer_4, created = Answer.objects.get_or_create(value=request.POST.get('answer_D'))
            obj = form.save(commit=False)
            obj.answer_2 = answer_2
            obj.answer_3 = answer_3
            obj.answer_4 = answer_4
            obj.is_prepared = True
            if accept == "True":
                obj.approved_by_admin = True
            messages.add_message(request, messages.SUCCESS, "Pytanie zostalo zapisane!")
            obj.save()
            if accept == "False":
                user.question_prepared.add(obj)
                return redirect('/workonquestion')
            return redirect('/acceptquestion')


@login_required()
@staff_member_required
def accept_question(request):
    """
    Functions handles accepting questions by admin
    :param request: Page request
    :return: Page on which administrator can accept questions prepared by users.
    """
    answered_questions = Question.objects.filter(approved_by_admin=False, is_prepared=True)
    questions_to_do_id = [question_id.id for question_id in answered_questions]
    if questions_to_do_id:
        random_question_id = random.choice(questions_to_do_id)
        random_question = Question.objects.get(id=random_question_id)
        form = QuestionForm(instance=random_question)
    else:
        form = random_question = None
    return render_to_response('admin/accept_question.html',
                              {
                                  'form': form,
                                  'question': random_question,
                              }, RequestContext(request))


@login_required()
@staff_member_required
def load_questions_field_of_question(request, field_of_question_id):
    """
    Function is responsible for reading a text file with all questions and correct answers and then creating corresponding records in database
    :param request: Page request
    :param field_of_question_id: Field of question id
    """
    field_of_question = FieldOfQuestion.objects.get(id=field_of_question_id)
    file_path = 'media/attachments/Questions/{}.txt'.format(field_of_question.name)
    question_answer = []
    with codecs.open(file_path, encoding='utf-8') as f:
        while True:
            question = f.readline()
            answer = f.readline()
            question_answer.append((question, answer[:-1]))
            if not answer:
                break  # EOF

    for number, item in enumerate(question_answer):
        if item[0]:
            correct_answer, created = Answer.objects.get_or_create(value=item[1], correct=True)
            question_created, success = Question.objects.get_or_create(question_number=number + 1, field_of_question=field_of_question, value=item[0])
            random_answer = random.randint(1, 4)
            # Unfortunately this is the only way how I can set random answers
            if random_answer == 1:
                question_created.answer_1 = correct_answer
            elif random_answer == 2:
                question_created.answer_2 = correct_answer
            elif random_answer == 3:
                question_created.answer_3 = correct_answer
            else:
                question_created.answer_4 = correct_answer
            question_created.save()


@login_required()
def start_test(request, field_of_question="all"):
    """

templates/mgr/all_questions.html
{% extends 'base.html' %}

{% block head-content %}
{% endblock %}

templates/mgr/choose_department.html
{% extends 'base.html' %}

{% block head-content %}
    <form role="form" action="" method="post">
        {% csrf_token %}
        <div class="col-lg-4 col-lg-offset-4">
            <div class="form-group">
                <label for="wydzial">Wybierz wydział</label>
                <select name="wydzial" id="wydzial" class="form-control">
                    {% for wydzial in departments %}
                        <option value="{{ wydzial.id }}">{{ wydzial }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="field_of_study">Wybierz kierunek</label>
                <select name="field_of_study" id="field_of_study" class="form-control">
                    {% for kierunek in field_of_study %}
                        <option value="{{ kierunek.id }}">{{ kierunek }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-lg btn-success"><span class="glyphicon glyphicon-ok"></span> Submit</button>
        </div>
    </form>
{% endblock %}

templates/mgr/create_test.html
{% extends "base.html" %}
{% load staticfiles %}

{% block script %}
    <script>
        $(document).ready(function () {
            var $all_questions = $('#all-questions tbody');
            {#        var $selected_questions = $('#selected-questions tbody');#}
            $('.btn-success.btn-sm').on('click', function () {
                {#            $('#selected-questions tbody').append($(this).closest('tr'));#}
                {#            $selected_questions.append($(this).closest('tr'));#}
                {#            console.log($(this).closest('tr'));#}
                var $closest_tr = $(this).closest('tr');
                $closest_tr.addClass('alert-success');
                $closest_tr.find('#add').hide();
                $closest_tr.find('#delete').show();
                $closest_tr.find("[type='checkbox']").prop('checked', true);
                {#            $selected_questions.append($closest_tr.html());#}
            });
            $('.btn-danger.btn-sm').on('click', function () {
                var $closest_tr = $(this).closest('tr');
                $closest_tr.removeClass('alert-success');
                $closest_tr.find('#delete').hide();
                $closest_tr.find('#add').show();
                $closest_tr.find("[type='checkbox']").prop('checked', false);
            });
            $('#clear-all').on('click', function () {
                var $checked_rows = $('#all-questions tbody').children('tr');
                $checked_rows.each(function () {
                    $(this).removeClass('alert-success');
                    $(this).find('#delete').hide();
                    $(this).find('#add').show();
                    $(this).removeClass('alert-success');
                    $(this).find("[type='checkbox']").prop('checked', false);
                });
            });
        });
    </script>
{% endblock %}
{% block head-content %}
    <form id="create-test" action="{% url "mgr.views.create_test" %}" method="post">
    {% csrf_token %}
        <div class="row">
            <table class="table" id="all-questions">
                <thead>
                <tr>
                    <th></th>
                    <th>Przedmiot</th>
                    <th>Pytanie</th>
                    <th>Dodaj/Usuń</th>
                </tr>
                </thead>
                <tbody>
                {% for question in question_approved %}
                    <tr id="{{ question.id }}">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ question.field_of_question.name }}</td>
                        <td>{{ question.value }}</td>
                        <td id="add">
                            <button type="button" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-ok"></span></button>
                        </td>
                        <td style="display: none" id="delete">
                            <button type="button" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span></button>
                        </td>
                        <td style="display: none;">
                            <label>
                                <input type="checkbox" name="{{ question.id }}"/>
                            </label>
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="2" align="center">
                        <button class="btn btn-danger btn-lg" type="button" id="clear-all"><span class="glyphicon glyphicon-trash"></span> Wyczyść wszystko
                        </button>
                    </td>
                    <td colspan="2" align="right">
                        <button class="btn btn-success btn-lg" type="submit" id="submit"><span class="glyphicon glyphicon-check"></span> Dodaj test</button>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        {#        <div class="row">#}
        {#            <table class="table table-hover" id="selected-questions">#}
        {#                <thead>#}
        {#                <tr>#}
        {#                    <th></th>#}
        {#                    <th>Przedmiot</th>#}
        {#                    <th>Pytanie</th>#}
        {#                </tr>#}
        {#                </thead>#}
        {#                <tbody>#}
        {#                </tbody>#}
        {#            </table>#}
        {#        </div>#}
    </form>
{% endblock %}

templates/mgr/display_options.html
{% extends 'base.html' %}

{% block head-content %}
    <div class="row">
        <div class="jumbotron">
            <h1>Informacje na temat Twojego konta!</h1>

            <div class="input-group input-group-lg col-md-3 col-lg-offset-4" style="margin-bottom: 10px">
                <span class="input-group-addon" id="sizing-addon1">Login</span>
                <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1" value="{{ user.username }}">
            </div>
            <div class="input-group input-group-lg col-md-3 col-lg-offset-4" style="margin-bottom: 10px">
                <span class="input-group-addon" id="sizing-addon1">Imię</span>
                <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1" value="{{ user.first_name }}">
            </div>
            <div class="input-group input-group-lg col-md-3 col-lg-offset-4" style="margin-bottom: 10px">
                <span class="input-group-addon" id="sizing-addon1">Nazwisko</span>
                <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1" value="{{ user.last_name }}">
            </div>
            <h3>Ilośc pytań przygotowanych: <span class="label label-default">{{ user.question_prepared.all|length }}</span></h3>
            <h3>Ilośc pytań zaakceptowanych: <span class="label label-success">{{ question_approved|length }}</span></h3>
            <p class="pull-left"><a class="btn btn-danger btn-lg" href="#" role="button"><span class="glyphicon glyphicon-backward"></span> Cofnij</a></p>
            <p class="pull-right"><a class="btn btn-info btn-lg" href="#" role="button"><span class="glyphicon glyphicon-ok"></span> Zapisz</a></p>
        </div>

    </div>
{% endblock %}

templates/mgr/display_results.html
{% extends "base.html" %}
{% load nvd3_tags %}
{% load staticfiles %}

{% block links %}
    {% include_chart_jscss %}
{% endblock %}
{% block script %}
    {% load_chart chart_type chart_data_0 "piechart_container_0" extra %}
{% endblock %}
{% block head-content %}
    <div class="row">
        <div class="col-sm-12 col-md-12 center-block">
            <div class="thumbnail">
                {% include_container "piechart_container_0" 400 370 %}
                <div class="caption">
                    <h3>Twoje wyniki!</h3>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/mgr/display_statistics.html
{% extends "base.html" %}

{% load nvd3_tags %}
{% load staticfiles %}

{% block links %}
    {% include_chart_jscss %}
{% endblock %}
{% block script %}
    {% load_chart chart_type_multi chart_data_multi "multibarhorizontalchart_container" extra %}
    {% load_chart chart_type_line chart_data_line "linechart_container" extra_line %}
    {% load_chart chart_type_pie chart_data_pie "piechart_container" extra_line %}
{% endblock %}

{% block head-content %}
    <ul class="nav nav-pills">
        <li role="presentation" class="active"><a data-toggle="tab" href="#sectionA">Line Chart</a></li>
        <li role="presentation"><a data-toggle="tab" href="#sectionB">Multi Chart</a></li>
        <li role="presentation"><a data-toggle="tab" href="#sectionC">Pie Chart</a></li>
    </ul>
    <div class="tab-content">
        <div id="sectionA" class="tab-pane fade in active">
            <h3>Line chart</h3>

            {% include_container "linechart_container" 800 1200 %}
        </div>
        <div id="sectionB" class="tab-pane fade">
            <h3>Multi Horizontal chart</h3>

            {% include_container "multibarhorizontalchart_container" 800 1200 %}
        </div>
        <div id="sectionC" class="tab-pane fade">
            <h3>Pie Chart</h3>

            {% include_container "piechart_container" 800 1200 %}
        </div>
    </div>

{% endblock %}

templates/mgr/question_form.html
{% if form.errors %}
    {% for key, value in form.errors.items %}
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <span class="sr-only">Error:</span>
            {{ key }}: {{ value }}
        </div>
    {% endfor %}
{% endif %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-primary">
            <div class="panel-heading">{{ question.question_number }} {{ question.field_of_question }}</div>
            <div class="panel-body" style="color: #000000">{{ question.value }}</div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-4">
        <div class="form-group">
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.label_tag }} {{ field }}
            {% endfor %}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-4">
        <div class="form-group">
            <label for="id_answer_1" style="width: 245.5px">A:<input class="form-control" id="answer_A" name="answer_A" type="text" readonly="True"
                                                                     value="{{ question.answer_1 }}"></label>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-4">
        <div class="form-group">
            <label for="id_answer_2">B:<input class="form-control" id="answer_B" name="answer_B" type="text" value="{{ question.answer_2|default_if_none:"" }}"></label>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-4">
        <div class="form-group">
            <label for="id_answer_3">C:<input class="form-control" id="answer_C" name="answer_C" type="text" value="{{ question.answer_3|default_if_none:"" }}"></label>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-4">
        <div class="form-group">
            <label for="id_answer_4">D:<input class="form-control" id="answer_D" name="answer_D" type="text" value="{{ question.answer_4|default_if_none:"" }}"></label>
        </div>
    </div>
</div>

{% block script %}
    <script>
        $(document).ready(function () {
            var answer_1 = "{{ question.answer_1 }}";
            if (answer_1.length > 32) {
                $('#answer_A').replaceWith('<textarea class="form-control" id="answer_A" name="answer_A" type="text" readonly="True" style="width: 450px; display:inline">{{ question.answer_1 }}</textarea>')
            }
            //TODO: Automatyczna zmiana inputa na textarea po wpisaniu 24 znakow
{#            var xTriggered = 0;#}
{#            $("[id^=answer_]").keypress(function(event){#}
{#                console.log("KEY PRESS");#}
{#                xTriggered++;#}
{#                if(xTriggered>=24){#}
{#                    console.log("ZMIANA");#}
{#                    var style = $(this).attr('style');#}
{#                    var text = $(this).text();#}
{#                    var textbox = $(document.createElement('textarea')).attr('style', style).attr('class','form-control');#}
{#                    $(this).replaceWith(textbox);#}
{#                    xTriggered=0;#}
{#                }#}
{#            })#}
{#        });#}
    </script>
{% endblock %}